<h1>FarmerLandProblem</h1>
<p>A farmer wants to farm their land with the maximum area where good land is present. The "land" is represented as a matrix with 1s and 0s, where 1s mean good land and 0s mean bad land. The farmer only wants to farm in a square of good land with the maximum area. Please help the farmer to find the maximum area of the land they can farm in good land.</p>

<h1>Solution</h1>
I recursively apply a filter that finds 2x2 squares until it cannot find any more. When applied to an already filtered matrix, it can find the next size square.

Example:
<pre>
0 1 1 0 1
1 1 0 1 0
0 1 1 1 0
1 1 1 1 0
1 1 1 1 1
0 0 0 0 0
</pre>

is filtered to

<pre>
0 0 0 0
0 0 0 0
0 1 1 0
1 1 1 0
0 0 0 0
</pre>

Notice, the 3x3 square turns into a 2x2. This applies to all sizes of squares (5x5 -> 4x4, 48X48 -> 47x47). If we find the highest square size, the next run-through will yield no 1s, thus we can stop.

With that theory, I track how many times the filter is applied before we hit the base case.

In [144]:
import numpy as np

# Recursive function to find the largest square of 1s in the land matrix
def largest_square(land_matrix, matrix_size = 2):
    # initialize variables for: the size of the input matirx (mxn), a filtered matrix of size (m-1) x (n-1) with default value 0, 
    # and a flag to check if all values in the filtered matrix are 0
    m = len(land_matrix)
    n = len(land_matrix[0])
    filtered_matrix = np.zeros((m - 1, n - 1), dtype=int)
    all_zeros = True

    # Apply a filter to the land matrix to find a 2x2 square of 1s. If found, set the corresponding position in the filtered matrix to 1.
    # Note, if this is applied to an already filtered matirx, it is checking for the next size square of 1s. (A 2x2 square of 2x2 squares is a 3x3 square of 1s, etc.)
    for i in range(m-1):
        for j in range(n-1):
            if (land_matrix[i][j] == 1 and land_matrix[i][j+1] == 1 and
                land_matrix[i+1][j] == 1 and land_matrix[i+1][j+1] == 1):
                filtered_matrix[i][j] = 1
                all_zeros = False
    
    # Base case: if all values in the filtered matrix are 0, return the size of the largest square found so far.
    # Note, if matrix_size = 2, that means no 2x2 squares were found. So we need to check if there are any 1s (1x1 square) in the original matrix.
    # Recursive case: if there are still 1s in the filtered matrix, call the function recursively with the filtered matrix and increment the matrix size.
    if all_zeros:
        if matrix_size == 2:
            for i in range(m):
                for j in range(n):
                    if land_matrix[i][j] == 1:
                        return 1
            return 0
        else:
            return matrix_size - 1
    else:
        return largest_square(filtered_matrix, matrix_size + 1)
    
    # The following code can tell you the top-left position of the first instance of the largest square found. 
    # Returning the filtered matrix could give you all top-left positions (The top left is the same index, even after filter is applied).
    '''
    if all_zeros:
        if matrix_size == 2:
            for i in range(m):
                for j in range(n):
                    if land_matrix[i][j] == 1:
                        return (i, j, 1)
        return (-1, -1, matrix_size)
    else:
        result = largest_square(filtered_matrix, matrix_size + 1)
        if result == (-1, -1, matrix_size + 1):
            for i in range(m-1):
                for j in range(n-1):
                    if filtered_matrix[i][j] == 1:
                        return (i, j, matrix_size)
        else:
            return result
    '''

In [ ]:
# This function first checks for 3x3 squares before the 2x2 squares. It was intended to be more efficient for large matrices with many 1s,
# but in practice, it seems to be within MOE for performance compared to the original function (for worst case). However, it may perform
# slightly better in the average case.
def largest_square3(land_matrix, matrix_size = 2):
    m = len(land_matrix)
    n = len(land_matrix[0])

    if (m < 3 or n < 3):
        return largest_square(land_matrix, matrix_size)
    
    filtered_matrix = np.zeros((m - 2, n - 2), dtype=int)
    all_zeros = True

    for i in range(m-2):
        for j in range(n-2):
            if (land_matrix[i][j] == 1 and land_matrix[i][j+1] == 1 and land_matrix[i][j+2] == 1 and
                land_matrix[i+1][j] == 1 and land_matrix[i+1][j+1] == 1 and land_matrix[i+1][j+2] == 1 and
                land_matrix[i+2][j] == 1 and land_matrix[i+2][j+1] == 1 and land_matrix[i+2][j+2] == 1):
                filtered_matrix[i][j] = 1
                all_zeros = False

    if all_zeros:
        return largest_square(land_matrix, matrix_size)
    else:
        return largest_square3(filtered_matrix, matrix_size + 2)



In [133]:
# Test suite for the original example, random matrices, and edge cases

n = np.random.randint(1, 20)
m = np.random.randint(1, 20)
test_matrix = np.random.randint(0, 2, (n, m))  

print(test_matrix)
print(largest_square3(test_matrix))

test_matrix = [[0, 1, 1, 0, 1],
    [1, 1, 0, 1, 0],
    [0, 1, 1, 1, 0],
    [1, 1, 1, 1, 0],
    [1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0]]

print(np.array(test_matrix))
print(largest_square3(test_matrix))

test_matrix = np.zeros((n, m), dtype=int)
print(test_matrix)
print(largest_square3(test_matrix))

test_matrix = np.ones((n, m), dtype=int)
print(test_matrix)
print(largest_square3(test_matrix))

[[1 1 1 0]
 [1 1 0 1]
 [0 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 0 0 0]
 [0 0 1 1]
 [0 1 1 0]
 [1 0 0 1]
 [0 1 1 1]
 [0 0 1 1]]
2
[[0 1 1 0 1]
 [1 1 0 1 0]
 [0 1 1 1 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [0 0 0 0 0]]
3
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
0
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
4


In [ ]:
# Tests the worst case, a large matrix of all 1s
import time

n = 1000
m = 1000
test_matrix = np.ones((n, m), dtype=int)

start_time = time.perf_counter()
print(largest_square(test_matrix))
end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time:.2f} seconds")

start_time = time.perf_counter()
print(largest_square3(test_matrix))
end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time:.2f} seconds")

1000
Elapsed time: 184.10 seconds
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
200
202
204
206
208
210
212
214
216
218
220
222
224
226
228
230
232
234
236
238
240
242
244
246
248
250
252
254
256
258
260
262
264
266
268
270
272
274
276
278
280
282
284
286
288
290
292
294
296
298
300
302
304
306
308
310
312
314
316
318
320
322
324
326
328
330
332
334
336
338
340
342
344
346
348
350
352
354
356
358
360
362
364
366
368
370
372
374
376
378
380
382
384
386
388
390
392
394
396
398
400
402
404
406
408
410
412
414
416
418
420
422
424
426
428
430
432
434
436
438
440
442
444
446
448
450
452
454
456
458
460
462
464
466
468
470
472
474
476
478
480
482
484
486
488
490
492
494
496
498
500
502
504
506
508
510

In [155]:
n = 10000
m = 10000
test_matrix = np.random.randint(0, 2, (n, m), dtype=int)

start_time = time.perf_counter()
print(largest_square(test_matrix))
end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time:.2f} seconds")

start_time = time.perf_counter()
print(largest_square3(test_matrix))
end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time:.2f} seconds")

5
Elapsed time: 68.15 seconds
5
Elapsed time: 57.41 seconds
